language: go

go:
        - 1.7.1

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -qq -y r-base
        - export R_LIBS="/tmp/Rlib"
        - mkdir $R_LIBS
        - echo "install.packages('GenSA', repos='http://cran.us.r-project.org')" | R --vanilla
        - echo "install.packages('e1071', repos='http://cran.us.r-project.org')" | R --vanilla
branches:
        only:
                - master
after_success:
        - bash <(curl -s https://codecov.io/bash)
