language: go

go:
        - 1.7.1

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -qq -y r-base
        - echo "install.packages('GenSA', repos='http://cran.us.r-project.org')" | R --vanilla
branches:
        only:
                - master
